[phases.setup]
nixPkgs = ["bun", "openssl"]

[phases.build]
cmds = [
  "bun install",
  "bunx prisma generate"
]

[phases.start]
cmd = "LD_LIBRARY_PATH=/nix/var/nix/profiles/default/lib bun src/index.ts"
