[phases.setup]
nixPkgs = ["bun", "openssl_3"]

[phases.build]
cmds = [
  "bun install",
  "bunx prisma generate"
]

[phases.start]
cmd = "bun src/index.ts"
env = { LD_LIBRARY_PATH = "/nix/store/khsdfxm8dz7qf7r35x235jl7v5pi87gn-openssl-3.0.16/lib" }


